### ISSUE TITLE
Publish to webstore

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed-screensharing-chrome-extension#1]
The extension should be released as a first version and published to the Chrome webstore (https://chrome.google.com/webstore/category/extensions) so we have an extension id and can add auto-installation code to the Spreed app.

Open tasks:
- [x] Add icons (see https://developer.chrome.com/apps/manifest/icons)
- [x] Write a description of the app including a couple of screenshots (see https://developer.chrome.com/webstore/images)
- [x] Create a Nextcloud account at the Chrome webstore (you might already have one)

cc @nickvergessen

**Comment by nickvergessen** [comment]
@jancborchardt also here, should we just use our logo as icon?
> ![bildschirmfoto vom 2017-01-31 11-33-55](https://cloud.githubusercontent.com/assets/213943/22461358/3913b890-e7a9-11e6-97ff-1f5da29b32fb.png)


And any idea for the screenshot?

**Comment by jancborchardt** [comment]
Yes, Nextcloud favicon. Also, please »Nextcloud Video calls app« as we call it like that everywhere.

For a screenshot, maybe let’s just use the one from https://github.com/nextcloud/spreed#spreed-video-calls for now? When we have screensharing in we need to take an additional one anyway and also add that to the readme.

**Comment by nickvergessen** [comment]
I think it should say screensharing somehow? because you don't need it for calling, just for screen sharing?

**Comment by jancborchardt** [comment]
»Screensharing for Nextcloud Video calls app«?

**Comment by nickvergessen** [comment]
https://chrome.google.com/webstore/detail/screensharing-for-nextclo/kepnpjhambipllfmgmbapncekcmabkol
