### ISSUE TITLE
Icon in top right toolbar needed?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed-screensharing-chrome-extension#4]
The extension adds this icon to the top right toolbar:
![capture du 2017-03-07 15-35-58](https://cloud.githubusercontent.com/assets/925062/23661104/e94f5170-034b-11e7-99ff-9248b1601690.png)

Is this really necessary? It seems to not do anything than link to nextcloud.com in the menu that opens. If we can avoid adding that icon we should, because the functionality is fully in the background.

cc @fancycode @Ivansss @nickvergessen

**Comment by nickvergessen** [comment]
I don't think there is a way around this.

**Comment by nickvergessen** [comment]
http://stackoverflow.com/a/37521405

**Comment by fancycode** [comment]
Dang, you beat me by 30 seconds ;-)

**Comment by jancborchardt** [comment]
Ah ok, thanks!
