### ISSUE TITLE
Broken in Chrome 71.0.3578.80

### ISSUE THREAD

**Issue by GrueneNeun** [nextcloud/spreed-screensharing-chrome-extension#5]
After clicking "Share Screen" in Nextcloud Talk there is no response anymore. Before updating Chrome everything worked well.

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/spreed/issues/1360

New Nextcloud Talk version 4.0.2 was released for Nextcloud 14
New Nextcloud Talk version 3.2.7 was released for Nextcloud 13
